name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia a master si es tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Usa el directorio raíz porque ahí está tu index.html
